# Generated by Django 6.0.3 on 2026-03-30 22:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0006_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbook",
            name="version",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.1"),
                help_text="Draft: 0.1, 0.2, etc. Released: 1.0, 2.0, etc.",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short descriptive name for the agent (e.g., 'Code Reviewer')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What this agent does and when to use it",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "playbook",
                    models.ForeignKey(
                        help_text="Parent playbook this agent belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="methodology.playbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("playbook", "name"),
                        name="unique_agent_name_per_playbook",
                    )
                ],
            },
        ),
    ]
