# Generated by Django 6.0 on 2026-04-14 16:16

import django.db.models.deletion
from django.db import migrations, models


def clear_old_phase_values(apps, schema_editor):
    """
    Clear old CharField phase values before converting to ForeignKey.
    
    Old phase values were free-text and workflow-scoped.
    New phases are playbook-scoped entities.
    Users will manually reassign activities to new phases after migration.
    """
    Activity = apps.get_model('methodology', 'Activity')
    Activity.objects.all().update(phase=None)


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0009_skill_playbook_scoped_with_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbook",
            name="version",
            field=models.DecimalField(
                decimal_places=1,
                default=0.1,
                help_text="Draft: 0.1, 0.2, etc. Released: 1.0, 2.0, etc.",
                max_digits=5,
            ),
        ),
        # Create Phase model first
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Phase name (e.g., 'Inception', 'Elaboration', 'Construction')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Phase description and purpose"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1, help_text="Display order within playbook"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "playbook",
                    models.ForeignKey(
                        help_text="Parent playbook containing this phase",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="methodology.playbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phase",
                "verbose_name_plural": "Phases",
                "ordering": ["playbook", "order", "name"],
            },
        ),
        # Clear old phase values before altering field
        migrations.RunPython(clear_old_phase_values, reverse_code=migrations.RunPython.noop),
        # Now alter the Activity.phase field to ForeignKey
        migrations.AlterField(
            model_name="activity",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional phase assignment for lifecycle stage grouping",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="methodology.phase",
            ),
        ),
        # Add constraints
        migrations.AddConstraint(
            model_name="phase",
            constraint=models.UniqueConstraint(
                fields=("playbook", "name"), name="unique_phase_name_per_playbook"
            ),
        ),
        migrations.AddConstraint(
            model_name="phase",
            constraint=models.UniqueConstraint(
                fields=("playbook", "order"), name="unique_phase_order_per_playbook"
            ),
        ),
    ]
