# Generated by Django 6.0 on 2026-05-01 17:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0011_rule_model_and_activity_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookversion',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Release or change narrative; aligns with change_summary over time.'),
        ),
        migrations.AddField(
            model_name='playbookversion',
            name='is_major',
            field=models.BooleanField(default=False, help_text='True when this row records a Release major bump.'),
        ),
        migrations.AddField(
            model_name='playbookversion',
            name='source',
            field=models.CharField(choices=[('author', 'Author'), ('release', 'Release'), ('pip', 'PIP'), ('admin', 'Admin')], default='author', max_length=20),
        ),
        migrations.AlterField(
            model_name='playbookversion',
            name='version_number',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='ProcessImprovementProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', help_text='e.g. pending, approved, implemented', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pips', to=settings.AUTH_USER_MODEL)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_improvement_proposals', to='methodology.playbook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='playbookversion',
            name='pip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_versions', to='methodology.processimprovementproposal'),
        ),
    ]
