# Generated by Django 6.0 on 2026-05-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("methodology", "0013_playbook_version_legacy_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbook",
            name="shared_with_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups that have access to this playbook",
                related_name="shared_playbooks",
                to="auth.group",
            ),
        ),
    ]
