# Generated by Django 6.0 on 2026-05-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0015_pip_act9_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processimprovementproposal",
            options={"ordering": ["-updated_at", "-pk"]},
        ),
        migrations.RenameIndex(
            model_name="pipchange",
            new_name="methodology_pip_id_9f4fcb_idx",
            old_name="m_pipchg_pip_ord",
        ),
    ]
