# Generated by Django 6.0 on 2026-05-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0017_playbook_public_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processimprovementproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing_galdr', 'Processing (Galdr)'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('accepted_partial', 'Partially Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=40),
        ),
    ]
