# Generated by Django 6.0 on 2026-05-25 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0019_activity_skills_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipchange',
            name='internal_ref',
            field=models.CharField(blank=True, default='', help_text='Optional label on ADD rows (e.g. #cdk-skill) for within-PIP LINK resolution.', max_length=64),
        ),
        migrations.AddField(
            model_name='pipchange',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('skill_activity', 'Skill → Activity'), ('rule_activity', 'Rule → Activity'), ('agent_activity', 'Agent → Activity'), ('activity_workflow', 'Activity → Workflow')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='pipchange',
            name='source_entity_ref',
            field=models.CharField(blank=True, default='', help_text='Source entity pk or #internal_ref for LINK/UNLINK.', max_length=64),
        ),
        migrations.AddField(
            model_name='pipchange',
            name='source_entity_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='pipchange',
            name='target_entity_ref',
            field=models.CharField(blank=True, default='', help_text='Target entity pk or #internal_ref for LINK/UNLINK.', max_length=64),
        ),
        migrations.AddField(
            model_name='pipchange',
            name='target_entity_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='pipchange',
            name='change_type',
            field=models.CharField(choices=[('ADD', 'ADD'), ('ALTER', 'ALTER'), ('DROP', 'DROP'), ('LINK', 'LINK'), ('UNLINK', 'UNLINK')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pipchange',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('Workflow', 'Workflow'), ('Activity', 'Activity'), ('Skill', 'Skill'), ('Agent', 'Agent'), ('Artifact', 'Artifact'), ('Rule', 'Rule')], default='', max_length=32),
        ),
        migrations.CreateModel(
            name='ActivityWorkflowMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order within the secondary workflow')),
                ('is_primary', models.BooleanField(default=False, help_text='True when this row mirrors the activity primary workflow FK')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_memberships', to='methodology.activity')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_activities', to='methodology.workflow')),
            ],
            options={
                'verbose_name': 'Activity workflow membership',
                'verbose_name_plural': 'Activity workflow memberships',
                'ordering': ['workflow', 'order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'workflow'), name='unique_activity_workflow_membership')],
            },
        ),
    ]
