# Generated by Django 6.0 on 2026-05-26 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0020_pip_link_unlink_and_activity_workflow_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Hidden', 'Hidden')], default='Public', max_length=20)),
                ('join_policy', models.CharField(choices=[('Auto-approve', 'Auto-approve'), ('Requires Approval', 'Requires Approval'), ('Invite Only', 'Invite Only')], default='Auto-approve', max_length=30)),
                ('category', models.CharField(choices=[('Engineering', 'Engineering'), ('Design', 'Design'), ('Research', 'Research'), ('Product', 'Product'), ('Private', 'Private'), ('Other', 'Other')], default='Other', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('self', 'Self'), ('invited', 'Invited'), ('invited_new', 'Invited (new user)')], default='self', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='methodology.team')),
            ],
            options={
                'verbose_name': 'Join Request',
                'verbose_name_plural': 'Join Requests',
                'ordering': ['requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='methodology.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'ordering': ['joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TeamPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_team_playbooks', to=settings.AUTH_USER_MODEL)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_playbooks', to='methodology.playbook')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_playbooks', to='methodology.team')),
            ],
            options={
                'verbose_name': 'Team Playbook',
                'verbose_name_plural': 'Team Playbooks',
                'ordering': ['added_at'],
                'unique_together': {('team', 'playbook')},
            },
        ),
    ]
