# Generated by Django 6.0 on 2026-05-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0022_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipchange',
            name='artifact_is_required',
            field=models.BooleanField(default=False, help_text='ADD/ALTER Artifact: required deliverable flag.'),
        ),
        migrations.AddField(
            model_name='pipchange',
            name='artifact_type',
            field=models.CharField(blank=True, default='Document', help_text='ADD/ALTER Artifact: Document, Template, Code, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='pipchange',
            name='insert_after_activity_ref',
            field=models.CharField(blank=True, default='', help_text='ADD Activity: activity pk or #internal_ref for ordering.', max_length=64),
        ),
        migrations.AddField(
            model_name='pipchange',
            name='parent_workflow_ref',
            field=models.CharField(blank=True, default='', help_text='ADD Activity: workflow pk or #internal_ref for pending ADD Workflow.', max_length=64),
        ),
        migrations.AddField(
            model_name='pipchange',
            name='phase_ref',
            field=models.CharField(blank=True, default='', help_text='ADD/ALTER Activity: phase pk or #internal_ref.', max_length=64),
        ),
        migrations.AddField(
            model_name='pipchange',
            name='produced_by_activity_ref',
            field=models.CharField(blank=True, default='', help_text='ADD Artifact: producer activity pk or #internal_ref.', max_length=64),
        ),
        migrations.AlterField(
            model_name='pipchange',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('Workflow', 'Workflow'), ('Activity', 'Activity'), ('Phase', 'Phase'), ('Skill', 'Skill'), ('Agent', 'Agent'), ('Artifact', 'Artifact'), ('Rule', 'Rule')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='pipchange',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('skill_activity', 'Skill → Activity'), ('rule_activity', 'Rule → Activity'), ('agent_activity', 'Agent → Activity'), ('activity_workflow', 'Activity → Workflow'), ('artifact_activity', 'Artifact → Activity')], default='', max_length=32),
        ),
    ]
